image: registry.gitlab.com/ccp5/dlpoly-py:latest
before_script:
  - python3 --version
  - python3 -m pip install -r requirements.txt

stages:
  - test
  - static

flake8:
  stage: static
  script:
    - flake8 --max-line-length=120 dlpoly/*.py
    - flake8 --max-line-length=120 tests/test_*.py

# pylint:
#  stage: static
#  allow_failure: true
#  script:
#    - pylint -d C0301 dlpoly/*.py
#    - pylint -d C0301 examples/*.py

# mypy:
#  stage: static
#  allow_failure: true
#  script:
#  - for i in dlpoly/*.py; do python -m mypy $i; done

tests:
  stage: test
  script:
    - python3 ./setup.py build
    - python3 ./setup.py install --user
      #    - python -m unittest discover -s tests -p 'test_*.py'
    - source ~/.bashrc
    - module load dl_poly
    - tox

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
