image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - static
  - build

flake8:
  stage: static
  script:
    - flake8 --max-line-length=120 dlpoly/*.py
    - flake8 --max-line-length=120 examples/*.py

pylint:
  stage: static
  allow_failure: true
  script:
    - pylint -d C0301 dlpoly/*.py      
    - pylint -d C0301 examples/*.py

mypy:
  stage: static
  allow_failure: true
  script:
  - for i in dlpoly/*.py; do python -m mypy $i; done

build:
  stage: build
  script: 
    - python3 ./setup.py build  
    - python3 ./setup.py install 
    - cd examples && ./test-config.py 
