stages:
  - test

build:
  image: python:3.7
  stage: test
  script: 
    - apt-get update -qy
    - apt-get install -y python3-dev python3-numpy-dev
    - python3 ./setup.py build  
    - python3 ./setup.py install 

