[build-system]
requires = [
    "setuptools >= 61.0.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "dlpoly-py"
description = "DLPoly python module for file manipulation."
authors = [{name = "Alin M Elena", email = "alinm.elena@gmail.com"},
           {name = "Jacob Wilkins", email = "jacob.wilkins@stfc.ac.uk"}]
requires-python = ">=3.9"
readme = "README.rst"
license = {text = "BSD-3-Clause"}
keywords = ["dlpoly", "molecular dynamics"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Chemistry",
]
dynamic = ["version"]

dependencies=[
    'numpy>=1.5.0',
    'matplotlib>=2.0.0',
    'ruamel.yaml',
    'ase == 3.23.0',
    'pint',
]


[tool.setuptools.dynamic]
version = {attr = "dlpoly.__version__"}

[project.optional-dependencies]
test = [
    'coverage',
    'pytest',
    'pytest-cov',
    'tox',
]
docs = [
    'sphinx',
]
lint = [
    'flake8',
]
all = ["dlpoly-py[test,docs,lint]"]

[project.urls]
Repository = 'https://gitlab.com/drFaustroll/dlpoly-py'

[tool.isort]
# Configuration of [isort](https://isort.readthedocs.io)
line_length = 100
force_sort_within_sections = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']

[tool.pytest.ini_options]
# Configuration for [pytest](https://docs.pytest.org)
python_files = "test_*.py"
addopts = '--cov-report xml'
pythonpath = ["."]

[tool.black]
line-length = 100

[tool.pylint.format]
max-line-length = 100
max-args = 10
good-names = ["e", "i", "j", "k"]
min-similarity-lines=9

[tool.numpydoc_validation]
# report on all checks, except the below
checks = [
    "all",
    "EX01",
    "SA01",
    "ES01",
]

exclude = [  # don't report on objects that match any of these regex
    '\.__repr__',
    '\.__str__',
    '\._$',
]
